### ISSUE TITLE
Missing package

### ISSUE THREAD

**Issue by kispuding** [benjiman/java-html-dsl#1]
The package com.benjiweber.typeref is missing from the project. Could you please give a hint how the NamedValue interface should look like? (missing import in Attribute.java interface)

Thanks a lot.

**Comment by benjiman** [comment]
Hello. The code for that package is here https://github.com/benjiman/lambda-type-references/blob/master/src/main/java/com/benjiweber/typeref/NamedValue.java

n.b. this hack will no longer work as of jdk9 - the ability to reflect on lambda param names was intentionally removed.
