### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by tipsy** [benjiman/java-html-dsl#2]
Hi @benjiman,

I want to copy-paste `MethodFinder` into my project (https://github.com/tipsy/j2html), but you don't have a license.

Is it okay with you if I do that?

**Comment by benjiman** [comment]
Go for it, but bear in mind that a lot of this stuff doesn't work in Java 9 as they removed the parameter reflection capability.

**Comment by tipsy** [comment]
Thanks, and thanks for the warning.
